//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Models.TournamentOrganizationRegistration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Models.TournamentOrganizationRegistration.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajdudicators Granted, Payment Due.
        /// </summary>
        public static string AdjucatorsGranted {
            get {
                return ResourceManager.GetString("AdjucatorsGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjudicators Confirmed.
        /// </summary>
        public static string AdjucatorsPaid {
            get {
                return ResourceManager.GetString("AdjucatorsPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjudicators Requested.
        /// </summary>
        public static string AdjucatorsWanted {
            get {
                return ResourceManager.GetString("AdjucatorsWanted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation to be Billed.
        /// </summary>
        public static string BilledOrganization {
            get {
                return ResourceManager.GetString("BilledOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Code.
        /// </summary>
        public static string BookingCode {
            get {
                return ResourceManager.GetString("BookingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select the organization to be billed..
        /// </summary>
        public static string ErrorBilledOrganizationMissing {
            get {
                return ResourceManager.GetString("ErrorBilledOrganizationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a status note, if the organization is dropped..
        /// </summary>
        public static string ErrorOrganizationStatusNoteMissing {
            get {
                return ResourceManager.GetString("ErrorOrganizationStatusNoteMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t auto-assign slots.
        /// </summary>
        public static string LockAutoAssign {
            get {
                return ResourceManager.GetString("LockAutoAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string OrganizationStatus {
            get {
                return ResourceManager.GetString("OrganizationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string OrganizationStatusDraft {
            get {
                return ResourceManager.GetString("OrganizationStatusDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string OrganizationStatusNote {
            get {
                return ResourceManager.GetString("OrganizationStatusNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams Granted, Payment Due.
        /// </summary>
        public static string TeamsGranted {
            get {
                return ResourceManager.GetString("TeamsGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams Confirmed.
        /// </summary>
        public static string TeamsPaid {
            get {
                return ResourceManager.GetString("TeamsPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams Requested.
        /// </summary>
        public static string TeamsWanted {
            get {
                return ResourceManager.GetString("TeamsWanted", resourceCulture);
            }
        }
    }
}
