//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.TournamentManagement.Finance {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.TournamentManagement.Finance.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjudicators.
        /// </summary>
        public static string AdjudicatorsCaption {
            get {
                return ResourceManager.GetString("AdjudicatorsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of adjudicators confirmed cannot be higher than granted..
        /// </summary>
        public static string ErrorAdjudicatorsPaidConfirmedOverGranted {
            get {
                return ResourceManager.GetString("ErrorAdjudicatorsPaidConfirmedOverGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already confirmed adjudicators cannot be withdrawn..
        /// </summary>
        public static string ErrorAdjudicatorsPaidNewBelowOld {
            get {
                return ResourceManager.GetString("ErrorAdjudicatorsPaidNewBelowOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment of organization {0} is already in the list below. If you need to change it, remove it first..
        /// </summary>
        public static string ErrorDuplicatePayment {
            get {
                return ResourceManager.GetString("ErrorDuplicatePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a booking code, an organization abbreviation or an organization name.
        /// </summary>
        public static string ErrorSearchTermMissing {
            get {
                return ResourceManager.GetString("ErrorSearchTermMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No registration found..
        /// </summary>
        public static string ErrorSearchTermNotFound {
            get {
                return ResourceManager.GetString("ErrorSearchTermNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already confirmed teams cannot be withdrawn..
        /// </summary>
        public static string ErrorTeamsPaidConfirmedNewBelowOld {
            get {
                return ResourceManager.GetString("ErrorTeamsPaidConfirmedNewBelowOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of teams confirmed cannot be higher than granted..
        /// </summary>
        public static string ErrorTeamsPaidConfirmedOverGranted {
            get {
                return ResourceManager.GetString("ErrorTeamsPaidConfirmedOverGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granted.
        /// </summary>
        public static string GrantedCaption {
            get {
                return ResourceManager.GetString("GrantedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal.
        /// </summary>
        public static string JournalButtonCaption {
            get {
                return ResourceManager.GetString("JournalButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        public static string PaidCaption {
            get {
                return ResourceManager.GetString("PaidCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment received.
        /// </summary>
        public static string PaymentReceivedNote {
            get {
                return ResourceManager.GetString("PaymentReceivedNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Payments.
        /// </summary>
        public static string PostPaymentsButtonCaption {
            get {
                return ResourceManager.GetString("PostPaymentsButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string TeamsCaption {
            get {
                return ResourceManager.GetString("TeamsCaption", resourceCulture);
            }
        }
    }
}
