//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Models.Tournament {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Models.Tournament.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Number of Adjudicators.
        /// </summary>
        public static string AdjucatorCap {
            get {
                return ResourceManager.GetString("AdjucatorCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjudication Policy (n - x, where n is number of teams and x is this value).
        /// </summary>
        public static string AdjucatorSubtract {
            get {
                return ResourceManager.GetString("AdjucatorSubtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief Adjudicators.
        /// </summary>
        public static string ChiefAdjudicators {
            get {
                return ResourceManager.GetString("ChiefAdjudicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Organisation.
        /// </summary>
        public static string HostingOrganization {
            get {
                return ResourceManager.GetString("HostingOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Reference.
        /// </summary>
        public static string PaymentReference {
            get {
                return ResourceManager.GetString("PaymentReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Deadline.
        /// </summary>
        public static string RegistrationEnd {
            get {
                return ResourceManager.GetString("RegistrationEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Start.
        /// </summary>
        public static string RegistrationStart {
            get {
                return ResourceManager.GetString("RegistrationStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Number of Teams.
        /// </summary>
        public static string TeamCap {
            get {
                return ResourceManager.GetString("TeamCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persons per Team.
        /// </summary>
        public static string TeamSize {
            get {
                return ResourceManager.GetString("TeamSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        public static string TermsConditionsLink {
            get {
                return ResourceManager.GetString("TermsConditionsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervasity (tournament limited to university societies or societies associated with a university).
        /// </summary>
        public static string UniversityRequired {
            get {
                return ResourceManager.GetString("UniversityRequired", resourceCulture);
            }
        }
    }
}
