//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.TournamentManagement.Report.Index {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.TournamentManagement.Report.Index.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List all adjudicators with their organization..
        /// </summary>
        public static string AdjudicatorsDescription {
            get {
                return ResourceManager.GetString("AdjudicatorsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjudicators.
        /// </summary>
        public static string AdjudicatorsHeading {
            get {
                return ResourceManager.GetString("AdjudicatorsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List all attendees with all properties..
        /// </summary>
        public static string AttendeesDescription {
            get {
                return ResourceManager.GetString("AttendeesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendees.
        /// </summary>
        public static string AttendeesHeading {
            get {
                return ResourceManager.GetString("AttendeesHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists for every booking code the name and address of the organization to be billed..
        /// </summary>
        public static string BillingAddressesDescription {
            get {
                return ResourceManager.GetString("BillingAddressesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Addresses.
        /// </summary>
        public static string BillingAddressesHeading {
            get {
                return ResourceManager.GetString("BillingAddressesHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Heading {
            get {
                return ResourceManager.GetString("Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists all attendees with incomplete personal data..
        /// </summary>
        public static string MissingPersonalDataDescription {
            get {
                return ResourceManager.GetString("MissingPersonalDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendees with Missing Personal Data.
        /// </summary>
        public static string MissingPersonalDataHeading {
            get {
                return ResourceManager.GetString("MissingPersonalDataHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists all organizations with confirmed team or adjudicator slots, where speakers and/or adjudicators are not registered yet..
        /// </summary>
        public static string MissingRegistrationsDescription {
            get {
                return ResourceManager.GetString("MissingRegistrationsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Speakers and Addjudicators.
        /// </summary>
        public static string MissingRegistrationsHeading {
            get {
                return ResourceManager.GetString("MissingRegistrationsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List all teams with their organization and speakers..
        /// </summary>
        public static string TeamsDescription {
            get {
                return ResourceManager.GetString("TeamsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string TeamsHeading {
            get {
                return ResourceManager.GetString("TeamsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
