//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Facade.SlotManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Facade.SlotManager.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are happy to inform you that {1} was allocated
        ///
        ///{2} Teams and
        ///
        ///{3} Adjudicators
        ///
        ///for {0}
        ///
        ///Your current balance is: {4}
        ///
        ///Please mind that these slots need to be confirmed with full payment by {5}. If we do not receive payment by this date, your slots will be reallocated to teams on the waitlist.
        ///
        ///For all details regarding your balance and payment, please proceed to your account statement under {6}..
        /// </summary>
        public static string AssignmentNotificationBody {
            get {
                return ResourceManager.GetString("AssignmentNotificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///  &lt;!-- HTML 4.x --&gt;
        ///&lt;meta charset=&quot;utf-8&quot;&gt;
        ///   &lt;!-- HTML5 --&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;p&gt;
        ///We are happy to inform you that {1} was allocated
        ///&lt;/p&gt;
        ///
        ///&lt;p&gt;
        ///{2} Teams and
        ///&lt;br /&gt;
        ///{3} Adjudicators
        ///&lt;/p&gt;
        ///
        ///&lt;p&gt;
        ///for {0}
        ///&lt;/p&gt;
        ///
        ///&lt;p&gt;
        ///Your current balance is: {4}
        ///&lt;/p&gt;
        ///
        ///&lt;p&gt;
        ///Please mind that these slots need to be confirmed with full payment by {5}. If we do not receive payment by this date, your slots [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AssignmentNotificationHTMLBody {
            get {
                return ResourceManager.GetString("AssignmentNotificationHTMLBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Slot Allocations.
        /// </summary>
        public static string AssignmentNotificationSubject {
            get {
                return ResourceManager.GetString("AssignmentNotificationSubject", resourceCulture);
            }
        }
    }
}
