//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.TournamentRegistration.GetRegistrationsPartial {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.TournamentRegistration.GetRegistrationsPartial.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjudicators.
        /// </summary>
        public static string AdjucatorsLabel {
            get {
                return ResourceManager.GetString("AdjucatorsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjudicators granted:.
        /// </summary>
        public static string AdjudicatorsGranted {
            get {
                return ResourceManager.GetString("AdjudicatorsGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting Payment.
        /// </summary>
        public static string AwaitingPaymentLabel {
            get {
                return ResourceManager.GetString("AwaitingPaymentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance:.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checklist.
        /// </summary>
        public static string Checklist {
            get {
                return ResourceManager.GetString("Checklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        public static string ConfirmedLabel {
            get {
                return ResourceManager.GetString("ConfirmedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization status:.
        /// </summary>
        public static string OrganizationStatus {
            get {
                return ResourceManager.GetString("OrganizationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speakers and adjudicators entered personal data.
        /// </summary>
        public static string PersonalDataEntered {
            get {
                return ResourceManager.GetString("PersonalDataEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following users did not provide enough personal data. Please direct them to do so..
        /// </summary>
        public static string PersonalDataMissing {
            get {
                return ResourceManager.GetString("PersonalDataMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register speakers and adjudicators.
        /// </summary>
        public static string RegisterSpeakersAndAdjudicators {
            get {
                return ResourceManager.GetString("RegisterSpeakersAndAdjudicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams granted:.
        /// </summary>
        public static string TeamsGranted {
            get {
                return ResourceManager.GetString("TeamsGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string TeamsLabel {
            get {
                return ResourceManager.GetString("TeamsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        public static string WaitingLabel {
            get {
                return ResourceManager.GetString("WaitingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Organization&apos;s Registrations.
        /// </summary>
        public static string YourRegistrationsHeading {
            get {
                return ResourceManager.GetString("YourRegistrationsHeading", resourceCulture);
            }
        }
    }
}
