//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.TournamentManagement.Organization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.TournamentManagement.Organization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot change the status of an organization to unknown..
        /// </summary>
        public static string ErrorStatusCannotBeChangedToUnknown {
            get {
                return ResourceManager.GetString("ErrorStatusCannotBeChangedToUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is to inform you that the approval status of 
        ///
        ///{0} 
        ///
        ///you registered for 
        ///
        ///{1} 
        ///
        ///has been changed to 
        ///
        ///{2} 
        ///
        ///.
        /// </summary>
        public static string StatusChangeEMailBody {
            get {
                return ResourceManager.GetString("StatusChangeEMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional notes: 
        ///
        ///{0}
        ///
        ///.
        /// </summary>
        public static string StatusChangeEMailBodyAdditionalNotes {
            get {
                return ResourceManager.GetString("StatusChangeEMailBodyAdditionalNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Additional notes: &lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;{0}&lt;/strong&gt;&lt;/p&gt;.
        /// </summary>
        public static string StatusChangeEMailBodyAdditionalNotesHTML {
            get {
                return ResourceManager.GetString("StatusChangeEMailBodyAdditionalNotesHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not need to take any further action at this stage. This change in status does not relate to the allocation of slots, which will be assigned later..
        /// </summary>
        public static string StatusChangeEMailBodyApproved {
            get {
                return ResourceManager.GetString("StatusChangeEMailBodyApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;You do not need to take any further action at this stage. This change in status does not relate to the allocation of slots, which will be assigned later.&lt;/p&gt;.
        /// </summary>
        public static string StatusChangeEMailBodyApprovedHTML {
            get {
                return ResourceManager.GetString("StatusChangeEMailBodyApprovedHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you believe your organisation has been wrongfully dropped, please reply to this e-mail..
        /// </summary>
        public static string StatusChangeEMailBodyDropped {
            get {
                return ResourceManager.GetString("StatusChangeEMailBodyDropped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;If you believe your organisation has been wrongfully dropped, please reply to this e-mail.&lt;/p&gt;.
        /// </summary>
        public static string StatusChangeEMailBodyDroppedHTML {
            get {
                return ResourceManager.GetString("StatusChangeEMailBodyDroppedHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;This is to inform you that the approval status of&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;{0}&lt;/strong&gt;&lt;/p&gt;
        ///&lt;p&gt;you registered for&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;{1}&lt;/strong&gt;&lt;/p&gt;
        ///&lt;p&gt;has been changed to &lt;strong&gt;{2}&lt;/strong&gt;&lt;/p&gt;.
        /// </summary>
        public static string StatusChangeEMailHTMLBody {
            get {
                return ResourceManager.GetString("StatusChangeEMailHTMLBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization status change for tournament.
        /// </summary>
        public static string StatusChangeEMailSubject {
            get {
                return ResourceManager.GetString("StatusChangeEMailSubject", resourceCulture);
            }
        }
    }
}
