//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Models.UserPropertyValueViewModel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Models.UserPropertyValueViewModel.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;true&quot; or &quot;false&quot; required.
        /// </summary>
        public static string NotBooleanError {
            get {
                return ResourceManager.GetString("NotBooleanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid country selected.
        /// </summary>
        public static string NotCountry {
            get {
                return ResourceManager.GetString("NotCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and/or time value required.
        /// </summary>
        public static string NotDateTimeError {
            get {
                return ResourceManager.GetString("NotDateTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal value required.
        /// </summary>
        public static string NotDecimalError {
            get {
                return ResourceManager.GetString("NotDecimalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address is required..
        /// </summary>
        public static string NotEMail {
            get {
                return ResourceManager.GetString("NotEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection from available options required.
        /// </summary>
        public static string NotInOptions {
            get {
                return ResourceManager.GetString("NotInOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer value required.
        /// </summary>
        public static string NotIntError {
            get {
                return ResourceManager.GetString("NotIntError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid person selected.
        /// </summary>
        public static string NotPerson {
            get {
                return ResourceManager.GetString("NotPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A phone number is required. The phone number must start with a + sign and the country code. It may only contain digits, spaces and dashes..
        /// </summary>
        public static string NotPhoneNumber {
            get {
                return ResourceManager.GetString("NotPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be in the range from {0} to {1}.
        /// </summary>
        public static string RangeError {
            get {
                return ResourceManager.GetString("RangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
    }
}
