//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.TournamentRegistration.Display {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.TournamentRegistration.Display.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Statement.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjudicators Granted, Awaiting Payment.
        /// </summary>
        public static string AdjucatorsAwaitingPayment {
            get {
                return ResourceManager.GetString("AdjucatorsAwaitingPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjudicators Confirmed.
        /// </summary>
        public static string AdjucatorsConfirmedLabel {
            get {
                return ResourceManager.GetString("AdjucatorsConfirmedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjudicators Waiting.
        /// </summary>
        public static string AdjucatorsWaitingLabel {
            get {
                return ResourceManager.GetString("AdjucatorsWaitingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjudicators with complete data.
        /// </summary>
        public static string AdjudicatorsCompletedLabel {
            get {
                return ResourceManager.GetString("AdjudicatorsCompletedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjudicators.
        /// </summary>
        public static string AdjudicatorsHeading {
            get {
                return ResourceManager.GetString("AdjudicatorsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        public static string CreditLabel {
            get {
                return ResourceManager.GetString("CreditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        public static string DebitLabel {
            get {
                return ResourceManager.GetString("DebitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Please select person).
        /// </summary>
        public static string DefaultFirstName {
            get {
                return ResourceManager.GetString("DefaultFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DefaultLastName {
            get {
                return ResourceManager.GetString("DefaultLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Registration.
        /// </summary>
        public static string EditLink {
            get {
                return ResourceManager.GetString("EditLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is already registered as adjudicator..
        /// </summary>
        public static string ErrorAdjudicatorAlreadyRegistered {
            get {
                return ResourceManager.GetString("ErrorAdjudicatorAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is already registered as speaker..
        /// </summary>
        public static string ErrorAdjudicatorAlreadySpeaker {
            get {
                return ResourceManager.GetString("ErrorAdjudicatorAlreadySpeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is already registered with another organization..
        /// </summary>
        public static string ErrorAdjudicatorAlreadyWithOtherOrganization {
            get {
                return ResourceManager.GetString("ErrorAdjudicatorAlreadyWithOtherOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is already registered as adjudicator..
        /// </summary>
        public static string ErrorSpeakerAlreadyAdjudicator {
            get {
                return ResourceManager.GetString("ErrorSpeakerAlreadyAdjudicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is already part of another team..
        /// </summary>
        public static string ErrorSpeakerAlreadyInOtherTeam {
            get {
                return ResourceManager.GetString("ErrorSpeakerAlreadyInOtherTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is already part of the team..
        /// </summary>
        public static string ErrorSpeakerAlreadyInTeam {
            get {
                return ResourceManager.GetString("ErrorSpeakerAlreadyInTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament Registration.
        /// </summary>
        public static string Heading {
            get {
                return ResourceManager.GetString("Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string PrintAccountStatementLink {
            get {
                return ResourceManager.GetString("PrintAccountStatementLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Registration.
        /// </summary>
        public static string RemoveLink {
            get {
                return ResourceManager.GetString("RemoveLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams and Adjudicators.
        /// </summary>
        public static string TeamsAndAdjudicatorsHeading {
            get {
                return ResourceManager.GetString("TeamsAndAdjudicatorsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams Granted, Awaiting Payment.
        /// </summary>
        public static string TeamsAwaitingPaymentLabel {
            get {
                return ResourceManager.GetString("TeamsAwaitingPaymentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams with complete data.
        /// </summary>
        public static string TeamsCompletedLabel {
            get {
                return ResourceManager.GetString("TeamsCompletedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams Confirmed.
        /// </summary>
        public static string TeamsConfirmedLabel {
            get {
                return ResourceManager.GetString("TeamsConfirmedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string TeamsHeading {
            get {
                return ResourceManager.GetString("TeamsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams Waiting.
        /// </summary>
        public static string TeamsWaitingLabel {
            get {
                return ResourceManager.GetString("TeamsWaitingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament Registration.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totals.
        /// </summary>
        public static string TotalLabel {
            get {
                return ResourceManager.GetString("TotalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Registration.
        /// </summary>
        public static string YourRegistrationHeading {
            get {
                return ResourceManager.GetString("YourRegistrationHeading", resourceCulture);
            }
        }
    }
}
